### ISSUE TITLE
Farm Rare infinite loop 

### ISSUE THREAD

**Issue by Majinek** [GkevinOD/MSL-Bot-AutoIT#3]
Hello found issue with farm rare script. It's normally working in battle mode and detects variant, rare, exotic astromons don't know if legendary didn't have a chance to spot one. Issue begins with catch mode it stucks there in infinite loop thought that .bmp files needed to be redone so i did that but still it didn't detect which astromon to catch. After manualy catching script won't record catch in log. It restarts script and second issue is that after manual catch it wants to stop auto battle in infinite loop

**Comment by GkevinOD** [comment]
So when it finds a rare astromon, it goes into catch mode but does not catch the astromon?

Does it go into catch mode then comes out and goes back in? I'll probably be creating a better algorithm for most of the script to make it more stable. Might take a few days, but i'll try to help out.

As for the second issue, that's normal because I have it too. I just havent fixed it yet.

**Comment by Majinek** [comment]
Don't know if this is issue or not implemented yet, when bot detects gem inventory full it stops rather than go and sell gems. Saw in code sell gems function and thought it does that.

**Comment by GkevinOD** [comment]
I am working on a version 4 with a better and more flexible system overall. Will probably come in around 3 days to 2 weeks. I work pretty fast, but expect no updates for now.
